framework:
    secret: '%env(APP_SECRET)%'
    
    session:
        handler_id: null
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 0
        gc_probability: 1
        gc_divisor: 100
        gc_maxlifetime: 1440
        
    csrf_protection: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file